invenio_base/config.py
tests/test_flash_security.py

global: configuration fixes

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/version.py

Invenio-Base v0.2.0

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/version.py

Invenio-Base v0.2.1

---

tests/test_i18n.py
tests/test_manage.py
tests/test_views.py

tests: test for /ping endpoint

---

invenio_base/decorators.py

decorators: code style improvements

---

.travis.yml
CHANGES.rst
RELEASE-NOTES.rst
invenio_base/config.py
invenio_base/version.py
requirements-devel.txt
setup.py

Invenio-Base v0.3.0

---

.coveragerc
AUTHORS.rst
MANIFEST.in
invenio_base/cmd.py
invenio_base/cookiecutter-invenio-base/cookiecutter.json
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/manage.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/__init__.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/celery.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/cli.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/config.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/factory.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/wsgi.py
pytest.ini
setup.py
tests/test_cmd.py

* Added startproject command which creates an skeleton
of a new invenio site. (Closes #28)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

cli: added startproject command

---

invenio_base/app.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/factory.py
tests/test_app.py

* Improves parameter naming in create_app_factory. (closes #32)
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

app: improvements to parameter naming

---

invenio_base/app.py
invenio_base/wsgi.py
tests/test_app.py

* Fixes quantified code analysis issues.
(closes #41)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

tests: quantified code fix

---

invenio_base/app.py
invenio_base/cmd.py
tests/test_app.py
tests/test_cmd.py

* Adds command to list known entry points in an a given Python
environment.

cli: list entry points command

---

invenio_base/version.py

version: post-release bump

---

MANIFEST.in
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/requirements-devel.txt
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/setup.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/templates/{{ cookiecutter.package_name }}/index.html
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/views.py
setup.py
tests/test_cmd.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

demo: search engine packages installation

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/version.py

release: v1.0.0a6

---

invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/config.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

cookiecutter: header template fix

---

invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/setup.py

demo: version bump of Invenio-Indexer>=1.0.0a2

---

invenio_base/app.py
tests/test_app.py

--
needed for https://github.com/zenodo/zenodo/pull/548

app: configurable URL map converters

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/setup.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/factory.py
invenio_base/version.py

cookiecutter: converters entry points + release v1.0.0a7

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/app.py
invenio_base/version.py
invenio_base/wsgi.py

* Fixes issue where keyword arguments passed to the application factory
was not passed onto the WSGI factory.

app: kwargs configuration for wsgi factory

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/app.py
invenio_base/version.py

* Adds configurable URL prefixes for blueprints.  (closes #72)

app: custom url_prefix per blueprint

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/version.py

release: v1.0.0a13

---

invenio_base/cli.py
invenio_base/cmd.py
tests/conftest.py

global: copyright years update

---

invenio_base/app.py
tests/test_app.py

* Adds support for specifying custom application class.
Related to inveniosoftware/invenio-oauth2server#73

app: custom application class

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_base/version.py

release: v1.0.0a14

---

MANIFEST.in
README.rst
RELEASE-NOTES.rst
docs/conf.py
docs/requirements.txt
invenio_base/__init__.py
run-tests.sh

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

docs: move to readthedocs.io

---

.gitignore
.travis.yml
CONTRIBUTING.rst
MANIFEST.in
docs/Makefile
docs/authors.rst
docs/changes.rst
docs/conf.py
docs/contributing.rst
docs/installation.rst
docs/make.bat
docs/usage.rst

* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>

global: release checklist

---

invenio_base/cli.py
tests/test_cmd.py

* Renames migrate_secret_key to migrate-secret-key.

cli: migrate_secret_key to migrate-secret-key

---

.travis.yml
examples/app.py
invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/setup.py

- updated example.py to pass the tests

tests: make them pass!

---

tests/test_cmd.py

tests: add `Flask.logging.default_handler` if not present

---

invenio_base/__init__.py
invenio_base/cli.py

docs: delete wrong documentation

---

invenio_base/__init__.py

docs: add documentation for cli commands

---

invenio_base/cli.py
tests/test_cmd.py

cli: fix for secret key migration test

---

examples/app.py
invenio_base/app.py
tests/test_app.py

* fixes the problem of global instance_path
* (addresses /inveniosoftware/pytest-invenio/issues/17)

app: reevaluate instance_path and static_folder variable

---

invenio_base/wsgi.py
setup.py
tests/test_app.py

wsgi: Update import for ProxyFix and DispatcherMiddleware

---

CHANGES.rst
invenio_base/version.py
invenio_base/wsgi.py

Needed by inveniosoftware/invenio-app#47

release: v1.1.0

---

.travis.yml
setup.py

global: bump flask version

---

CHANGES.rst
invenio_base/version.py

release: v1.2.3

---

invenio_base/cli.py
invenio_base/wsgi.py
pytest.ini
run-tests.sh

Addresses inveniosoftware/opensource#65

Isort fixing

---

.github/workflows/tests.yml
invenio_base/app.py
setup.cfg
tests/test_app.py
tests/test_cmd.py

:heart: Thank you for your contribution!
Fix Invenio-Base to work with recently released Flask v2.1
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the …

global: Flask v2.1 support

---

invenio_base/__init__.py
setup.cfg

This reverts commit 007909b79ce85ed13152f91a36c85c2fbf233c83.
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current …

Revert "setup: upper pin werkzeug"

---

CHANGES.rst
invenio_base/__init__.py
setup.cfg

:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …

installation: pin Flask to <2.3.0

---

CHANGES.rst
invenio_base/__init__.py
setup.cfg

- installation: pin Werkzeug<2.3.0
- release: v1.2.15

Pin Werkzeug<2.3.0 and release v1.2.15

---

CHANGES.rst
invenio_base/__init__.py
invenio_base/app.py
setup.cfg

* allows to pass entry points to execute functions just after the app is instantiated
* closes https://github.com/inveniosoftware/invenio-base/issues/171

app: add init_functions_loader

---

CHANGES.rst
invenio_base/__init__.py
invenio_base/urls/builders.py
tests/test_urls.py

- **urls: support converters in create_invenio_apps_urls_builder_factory**
- **:package: release: v2.2.0**
- close #187

close #187 ; account for converters
