- invenio_base/static/js/settings.js
- invenio_base/templates/base/scripts_base.html
- invenio_base/templates/base/stylesheets_base.html
* NEW Adds `jsoneditor` dependency to r.js settings.
* BETTER Replaces `select2.min` with `select2` to simplify debugging.
* FIX Fixes a bug which, under certain conditions, led to wrong asset
links when working with ASSET_DEBUG=True.
Co-authored-by: Tibor Simko <tibor.simko@cern.ch>
(extracted from https://github.com/inveniosoftware/invenio/pull/3380)
> templates: asset improvements

- docs/index.rst
* BETTER Moves invenio-base's doc base.rst from invenio/docs/base.rst
to invenio-base/docs/base.rst.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
> base: move base.rst from invenio to invenio-base

- .travis.yml
- pytest.ini
- setup.py
* FIX pytest 2.8.0 removed functionality used for tests. This removes
calls to the removed functions.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
> tests: fix pytest >=2.8.0 breaking

- invenio_base/static/js/settings.js
* FIX corrects the d3.js library path.
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> installation: fix for d3 path

- invenio_base/config.py
* Removes unnecessary packages from .travis.invenio.cfg.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
> travis: removal of unnecessary packages

- .travis.yml
- MANIFEST.in
- docs/conf.py
- docs/index.rst
* Monkeypatch the test that complains on nonlocal image URI.
* Sidenote: if `mock>=1.1`, `mock._is_magic` is not available but travis uses the old one
> docs: build the docs in strict mode

- invenio_base/__init__.py
- invenio_base/app.py
- invenio_base/cmd.py
- tests/test_cmd.py
* Changed CLI command start project, which creates an skeleton
of a new invenio site, to 'instance create'. (closes #28)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> cli: changed startproject command

- invenio_base/__init__.py
- invenio_base/cmd.py
- tests/test_cmd.py
* Amends remaining "start project" occurrences by "create instance"
terminology in the output messages and the documentation.
(addresses #28)
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docs: from `startproject` to `instance create`

- invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/setup.py
* Adds missing dependencies for Invenio-Base and Invenio-Config.
(closes #64)
> cookiecutter: addition of missing dependencies

- invenio_base/app.py
* Fixes issue with Flask not setting app.debug until after the
application creation, causing e.g. template auto-reloading or
Flask-DebugToolbar to not be correctly initialized.
> app: debug state initialization fix

- invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/setup.py
- invenio_base/cookiecutter-invenio-base/{{ cookiecutter.site_name }}/{{ cookiecutter.package_name }}/config.py
* FIX Bumps minimal required version of Invenio-Theme and fixes default
settings template name.  (closes inveniosoftware/invenio#3756)
--
cc @lukasheinrich
> cookiecutter: theme config fix and version bump

- CHANGES.rst
- RELEASE-NOTES.rst
- docs/api.rst
- invenio_base/app.py
- invenio_base/signals.py
- invenio_base/version.py
- tests/test_signals.py
The idea behind the PR is that you can hook into the application creation process. In particular if you would like to e.g. modify the Flask application object. E.g. on Zenodo we need to disable strict slashes on the URL map, which has to happen fore you start adding anything to the URL map. Hence something like this:
```python
from invenio_app.factory import create_app, create_api
from invenio_base.signals import app_created
def disable_strict_slashes(sender, app=None):
app.url_map.strict_slashes = False
app_created.connect(disable_strict_slashes, sender=create_app)
app_created.connect(disable_strict_slashes, sender=create_api)
```
> signals: application creation signals

- invenio_base/app.py
- tests/test_app.py
* Modifies the `invenio_base.app.blueprint_loader` to also accept a
callable. (closes #132)
> app: accept callable for blueprints

- invenio_base/app.py
- tests/test_app.py
- tests/test_cmd.py
* Refactors tests calling a sample cli test-cmd.
* Modifies test_migrate_secret_key() to expect error
code 1 instead of -1.
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
> tests: fix cli test command

- CHANGES.rst
- invenio_base/version.py
- invenio_base/wsgi.py
- tests/test_wsgi.py
* The general problem solved here: whenever we need to take into
any of the following headers set by a proxy: `X-Forwarded-For`,
`X-Forwarded-Proto`, `X-Forwarded-Host`, `X-Forwarded-Port`,
or `X-Forwarded-Prefix` we can fine tune it with the new
configuration variable (see docstring for more info).
* The concrete problem solved here: when Invenio is running
behind a proxy which does SSL termination, the
`X-Forwarded-Proto` header is ignored causing the Flask
application to generate URLs with the wrong HTTP scheme.
With this change the `x_proto` parameter can be configured
so the header is taken into account and `url_for` generates
the correct URLs.
Before, having one proxy in front of the app that would send
`X-Forwarded-Proto: https`, would make the Flask app generate …
> wsgi: make proxy fix fully configurable

- .coveragerc
- invenio_base/cli.py
- setup.py
- tests/test_cmd.py
Changes:
* Removes installation dependency on cookiecutter
* Remove coverage file in order to omit the folder
* Remove create command: It was only launching an deprecated message. It was set up 2 years ago, I think by now the community is aware enough of cookiecutter and does not use the command anymore.
> dependencies: remove cookiecutter

- CHANGES.rst
- invenio_base/__init__.py
- invenio_base/app.py
As described in https://bugs.python.org/issue31558, ths improves memory usage in prefork-style runtime, like uWSGI and Celery.
Tested locally with 40-50% memory savings on Celery and uWSGI.
> Add `gc.freeze()` call and release v1.2.17

- CHANGES.rst
- invenio_base/__init__.py
- invenio_base/app.py
- invenio_base/urls/__init__.py
- invenio_base/urls/builders.py
- invenio_base/urls/helpers.py
- invenio_base/urls/proxies.py
- tests/test_urls.py
As presented on telecon 2025-02-11, this introduces `invenio_url_for` a url generating helper to build urls of any app within any app. 
I'll provide a "developer commentary" to highlight the functioning, some of the decisions and places where feedback would be appreciated.
Over the next days I will post the PRs for modules that integrate this to make it even clearer how this is to be used and what benefits it gives us.
Order of merges (those with same numbers can be done in parallel, order shouldn't matter):
1- invenio-base: This one
2- invenio-app: https://github.com/inveniosoftware/invenio-app/pull/98 
3- invenio-rdm-records (preparatory PR to prevent breakage) : https://github.com/inveniosoftware/invenio-rdm-records/pull/1962
4- invenio-records-resources: …
> urls: implement cross-app way to generate urls

- .github/workflows/pypi-publish.yml
Needed to switch to later version of ubuntu for publish task and so switched it to use the common pypi-publish GA workflow.
> ci: use shared pypi publish workflow

- invenio_base/app.py
- invenio_base/cli.py
- invenio_base/utils.py
- tests/test_cmd.py
- tests/test_urls.py
* UserWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html. The
pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.
> fix: pkg_resources DeprecationWarning

- invenio_base/app.py
- invenio_base/cli.py
- invenio_base/utils.py
* importlib.metadata.entry_points of python3.9 can contain duplicates.
duplicates create errors on the caller side. the rest of the code
assumes that the return value has no duplicates.
> fix: python3.9 can contain duplicates
